config/routes.rb
Cvcr::Application.routes.draw do

  #resources :payment_notifications, :line_items, :carts, :sessions

  root :to => 'pages#show', :id => 0

  match '/auth/failure' => 'authentications#failure'
  match '/auth/:provider/callback' => 'authentications#create'
  match '/pages/:id' => 'pages#show', :as => :page
  match '/products/:id' => 'products#show', :as => :product
  match '/sections/:id' => 'sections#show', :as => :section
  match '/areas/:id' => 'main_areas#show', :as => :main_area
  match '/payment_notifications' => 'payment_notifications#create'
  match '/line_items' => 'line_items#create'
  match '/line_items/:id/increment' => 'line_items#increment'
  match '/line_items/:id/decrement' => 'line_items#decrement'
  match '/line_items/:id/destroy' => 'line_items#destroy'
  match '/line_items/:id/set_grind' => 'line_items#set_grind'
  match '/cart' => 'carts#show'
  match '/cart/new' => 'carts#destroy'
  #match '/cart' => 'carts#show'

  match '/test' => 'test#show'

  get 'sessions/new'
  #get 'registrations/edit'
  #get 'registrations/new'
  #get 'authentications/index'
  #get 'authentications/create'
  #get 'authentications/destroy'

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, :controllers => {:registrations => 'registrations'}

end

app/models/cart.rb
class Cart < ActiveRecord::Base

  has_many :line_items

  def total_price
    # convert to array so it doesn't try to do sum on database directly
    line_items.to_a.sum(&:full_price)+total_shipping
  end

  def total_shipping
    price_1_2 = 5.6
    price_3_6 = 12.35
    price_7_8 = 16.85
    price_other = 0
    if total_items > 8
      price_other
    elsif total_items >= 7
      price_7_8
    elsif total_items >= 3
      price_3_6
    elsif total_items >= 1
      price_1_2
    else
      price_other
    end
  end

  def total_items
    # convert to array so it doesn't try to do sum on database directly
    line_items.to_a.sum(&:quantity)
  end

  # keep for unencrypted flows - doubt we'll ever need
# def paypal_url(return_url, notify_url)
#   values = {
#       :business => 'nik.cimino-facilitator@gmail.com',
#       :cmd => '_cart',
#       :upload => 1,
#       :return => return_url,
#       :invoice => id,
#       :notify_url => notify_url,
#
#   }
#   line_items.each_with_index do |item, index|
#     values.merge!({
#                       "amount_#{index+1}" => item.unit_price,
#                       "item_name_#{index+1}" => "#{item.product.name} - #{item.grind}",
#                       "item_number_#{index+1}" => item.id,
#                       "quantity_#{index+1}" => item.quantity
#                   })
#   end
#   'https://www.sandbox.paypal.com/cgi-bin/webscr?' + values.to_query
# end


# best API key/value maching I've found is at:
# https://developer.paypal.com/webapps/developer/docs/classic/paypal-payments-standard/integration-guide/Appx_websitestandard_htmlvariables/#id08A6HI0J0VU
  def paypal_encrypted(return_url, notify_url)

    values = {
        :business => APP_CONFIG[:paypal_email],
        :cmd => '_cart',
        :upload => 1,
        :return => return_url,
        :invoice => id,
        :notify_url => notify_url,
        :cert_id => APP_CONFIG[:paypal_cert_id]
    }

    line_items.each_with_index do |item, index|
      item_name = item.product.name
      if item.product.supports_grind
        item_name += " - #{item.grind}"
      end
      values.merge!({
        "amount_#{index+1}" => item.unit_price,
        "item_name_#{index+1}" => item_name,
        "item_number_#{index+1}" => item.id,
        "quantity_#{index+1}" => item.quantity
      })
    end

    values.merge!({
      "handling_cart" => total_shipping
    })

    encrypt_for_paypal(values)
  end

  #PAYPAL_CERT_PEM = File.read("#{Rails.root}/#{APP_CONFIG[:paypal_cert]}")
  PAYPAL_CERT_PEM = File.read("#{Rails.root}/certs/paypal_cert.pem")
  APP_CERT_PEM = File.read("#{Rails.root}/certs/app_cert.pem")
  APP_KEY_PEM = File.read("#{Rails.root}/certs/app_key.pem")

  def encrypt_for_paypal(values)
    signed = OpenSSL::PKCS7::sign(OpenSSL::X509::Certificate.new(APP_CERT_PEM), OpenSSL::PKey::RSA.new(APP_KEY_PEM, ''), values.map { |k, v| "#{k}=#{v}" }.join("\n"), [], OpenSSL::PKCS7::BINARY)
    OpenSSL::PKCS7::encrypt([OpenSSL::X509::Certificate.new(PAYPAL_CERT_PEM)], signed.to_der, OpenSSL::Cipher::Cipher::new("DES3"), OpenSSL::PKCS7::BINARY).to_s.gsub("\n", "")
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = @current_cart
  end

  def destroy
    session.delete(:cart_id)
    @cart = @current_cart
    redirect_to cart_url
  end
end

app/views/carts/purchase.html.erb
<% title "Purchase Successful" %>

<p><strong>Thank you for your order!</strong> We will process it within one business day.</p>
<p><%= link_to "Back to Products", products_path %></p>

app/views/carts/show.html.erb
<% title "Shopping Cart" %>

<div class="container content-holder">
  <h1><%= yield :title  %></h1>
  <table class="table table-striped">
    <tr>
      <th>Product</th>
      <th>Options</th>
      <th>Qty</th>
      <th class="price">Unit Price</th>
      <th class="price">Full Price</th>
    </tr>
    <% for line_item in @cart.line_items %>
      <tr class="<%= cycle :odd, :even %>">
        <td><%= link_to line_item.product.name, line_item.product %></td>
        <td class="options">
          <% if line_item.product.supports_grind %>
            <%= form_for line_item, :html => { :class => "submit_on_change" }, :url => { :action => "set_grind", :controller => "line_items", :id => line_item } do |grind_form| %>
              <%= select_tag( :grind, options_for_select( [ [ "Whole Bean", "Whole Bean" ], [ "Ground", "Ground" ] ], selected: "#{line_item.grind}" ).html_safe  ) %>
              <%#= grind_form.submit() %>
            <% end %>
          <% end %>
        </td>
        <td class="qty">
          <% if line_item.quantity > 1 %>
            <%= link_to '<i class="icon-minus-sign"></i>'.html_safe, :controller => 'line_items', :action => 'decrement', :id => line_item %>
          <% else %>
            <%= link_to '<i class="icon-minus-sign" data-confirm="This will remove the item from your cart, continue?"></i>'.html_safe, :controller => 'line_items', :action => 'decrement', :id => line_item %>
          <% end %>
          <%= line_item.quantity %>
          <%= link_to '<i class="icon-plus-sign"></i>'.html_safe, :controller => 'line_items', :action => 'increment', :id => line_item %>
        </td>
        <td class="price"><%= number_to_currency(line_item.unit_price) %></td>
        <td class="price">
          <%= number_to_currency(line_item.full_price) %>
          <%= link_to '<i class="icon-remove-sign" title="Remove" data-confirm="This will remove the item from your cart, continue?"></i>'.html_safe, :controller => 'line_items', :action => 'destroy', :id => line_item %>
        </td>
      </tr>
    <% end %>
    <tr class="<%= cycle :odd, :even %>">
      <td><i>Shipping</i></td>
      <td></td>
      <td></td>
      <td></td>
      <td class="price"><%= number_to_currency(@cart.total_shipping) %>&nbsp;&nbsp;&nbsp;&nbsp;</td>
    </tr>
    <tr>
      <td class="total price" colspan="5">
        Total: <%= number_to_currency @cart.total_price %> &nbsp;&nbsp;&nbsp;
      </td>
    </tr>
  </table>

  <div class="row">
    <div class="span6">
      <%= link_to "Continue Shopping", url_for(@area1) %> |
      <%= link_to "Empty Cart", cart_new_url, :data => { :confirm => "Are you sure you want to empty your cart?", :method => :delete } %>
    </div>
    <div class="span6 text-right">
      <%= form_tag APP_CONFIG[:paypal_url] do %>
        <%= hidden_field_tag :cmd, "_s-xclick" %>
        <% if Rails.env.production? %>
          <%= hidden_field_tag :encrypted, @cart.paypal_encrypted(URI.join(root_url, url_for(@area1)), payment_notifications_url(:secret => APP_CONFIG[:paypal_secret])) %>
        <% else %>
          <%= hidden_field_tag :encrypted, @cart.paypal_encrypted(URI.join(root_url, url_for(@area1)), "http://67.173.246.78:3000/payment_notifications?secret=supersecret") %>
        <% end %>
        <input type="image" src="https://www.paypal.com/en_US/i/btn/btn_buynowCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!" />
      <% end %>
    </div>
  </div>

</div>