config/routes.rb
Cvcr::Application.routes.draw do

  #resources :payment_notifications, :line_items, :carts, :sessions

  root :to => 'pages#show', :id => 0

  match '/auth/failure' => 'authentications#failure'
  match '/auth/:provider/callback' => 'authentications#create'
  match '/pages/:id' => 'pages#show', :as => :page
  match '/products/:id' => 'products#show', :as => :product
  match '/sections/:id' => 'sections#show', :as => :section
  match '/areas/:id' => 'main_areas#show', :as => :main_area
  match '/payment_notifications' => 'payment_notifications#create'
  match '/line_items' => 'line_items#create'
  match '/line_items/:id/increment' => 'line_items#increment'
  match '/line_items/:id/decrement' => 'line_items#decrement'
  match '/line_items/:id/destroy' => 'line_items#destroy'
  match '/line_items/:id/set_grind' => 'line_items#set_grind'
  match '/cart' => 'carts#show'
  match '/cart/new' => 'carts#destroy'
  #match '/cart' => 'carts#show'

  match '/test' => 'test#show'

  get 'sessions/new'
  #get 'registrations/edit'
  #get 'registrations/new'
  #get 'authentications/index'
  #get 'authentications/create'
  #get 'authentications/destroy'

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, :controllers => {:registrations => 'registrations'}

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_and_belongs_to_many :image_handlers
  has_and_belongs_to_many :sections
  attr_accessible :description, :image, :name, :price, :section_ids, :image_handler_ids, :active, :content, :supports_grind
  validates_presence_of :name, :price
  def to_param
    "#{id}-#{name.parameterize}"
  end
  scope :recent, find(:all, :order => "updated_at")
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all

    respond_to do |format|
      if @products
        format.html
        format.json { render json: @products }
      else
        format.html { redirect_to :admin_root }
        format.json { render json: @products.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product
        format.html
        format.json { render json: @product }
      else
        format.html { redirect_to :admin_root }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/views/products/show.html.erb
<% title @product.name %>

<div class="container content-holder">
  <% if content_for?(:title) %>
    <h1><%= yield :title  %></h1>
    <hr />
  <% end %>

  <div class="row">
    <div class="span5 product-image">
      <%= image_tag(@product.image_handlers.first.image.url) if !@product.image_handlers.first.image.file.nil? && @product.image_handlers.first.image.file.exists? %>
    </div>
    <div class="product-content">
      <h3 class="currency">
        <%= number_to_currency(@product.price, :unit => "$") %>
        <%= link_to "Add to Cart", line_items_path(:product_id => @product),
                    :method => :post, :class => 'btn btn-primary btn-large pull-right' %>
      </h3>
      <hr class="lightrule" />
      <%= @product.content ? @product.content.html_safe : "" %>
    </div>
  </div>
  <br />

</div>